backend:
  name: github
  repo: demoniry/demoni-www-next
display_url: https://demoniry.fi
media_folder: static/uploads
public_folder: "/uploads"
collections:
  - name: pages
    label: Pages
    label_singular: Page
    folder: content/pages
    create: true
    extension: md
    fields:
      - name: title
        label: Title
        widget: string
      - name: description
        label: Description
        widget: text
        hint:
          A short description of page's contents as often seen in Google
          results.
      - name: type
        label: Special page type
        widget: select
        default: ""
        options:
          - label: None
            value: ""
          - label: Board
            value: board
      - name: body
        label: Content
        widget: markdown
        buttons:
          - italic
          - link
          - bulleted-list
          - numbered-list
          - heading-two
  - name: news
    label: News
    label_singular: News item
    folder: content/news
    create: true
    extension: md
    fields:
      - name: title
        label: Title
        widget: string
      - name: date
        label: Date
        widget: date
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
      - name: description
        label: Summary
        widget: text
        hint: A short version of the article's contents.
      - name: body
        label: Content
        widget: markdown
        buttons:
          - italic
          - link
          - bulleted-list
          - numbered-list
          - heading-two
  - name: boards
    label: Boards
    label_singular: Board
    folder: content/boards
    create: true
    delete: false
    identifier_field: year
    extension: yml
    editor:
      preview: false
    fields:
      - name: year
        label: Year of activity
        hint: The year the board began its work.
        widget: string
      - name: members
        label: Members
        label_singular: member
        widget: list
        fields:
          - name: name
            label: Name
            widget: string
          - name: position
            label: Position
            required: false
            widget: string
          - name: portrait
            label: Portrait
            required: false
            widget: image
            allow_multiple: false
  - name: settings
    label: Site settings
    editor:
      preview: false
    files:
      - name: navigation
        label: Navigation
        file: content/settings/navigation.yml
        fields:
          - name: items
            label: Menu items
            label_singular: Menu item
            widget: list
            fields:
              - name: title
                label: Title
                widget: string
              - name: destination
                label: Destination
                widget: relation
                collection: pages
                searchFields: ["title"]
                valueField: title
              - name: items
                label: Subitems
                required: false
                widget: list
                fields:
                  - name: title
                    label: Title
                    widget: string
                  - name: destination
                    label: Destination
                    widget: relation
                    collection: pages
                    searchFields: ["title"]
                    valueField: title
