backend:
  name: github
  repo: demoniry/demoni-www-next
media_folder: static/uploads
public_folder: "/uploads"
collections:
  - name: pages
    label: Pages
    label_singular: Page
    folder: content/pages
    create: true
    extension: md
    fields:
      - name: title
        label: Title
        widget: string
      - name: description
        label: Description
        widget: text
        hint:
          A short description of page's contents as often seen in Google
          results.
      - name: body
        label: Content
        widget: markdown
        buttons:
          - italic
          - link
          - bulleted-list
          - numbered-list
          - heading-two
